dTree:
  max_depth: 10
dataset:
  iFile:
    cFlds:
    - d1
    - d2
    - d3
    iFlds:
    - i1
    - i2
    iSize:
    - 2
    - 3
    nFlds:
    - n1
    name: data/crx2.csv
    yFld: class
    yType: c
  idFld: id
  seqFiles:
  - fields: id,time,item
    fldname: seqfld1
    iSize: 2
    maxGap: null
    maxLen: 3
    maxSize: 4
    maxWin: 4
    minGap: null
    minSup: 5
    minSupProb: null
    name: data/crx2_seq1.csv
  - fields: id,time,item
    fldname: seqfld2
    iSize: 3
    maxGap: null
    maxLen: 3
    maxSize: 4
    maxWin: 4
    minGap: null
    minSup: 5
    minSupProb: null
    name: data/crx2_seq2.csv
  traFiles:
  - fldname: trafld1
    iSize: 3
    name: data/crx_tra1.csv
  - fldname: trafld2
    iSize: 4
    name: data/crx_tra2.csv
oPath: result_crx
